pkg/ccm/loadbalancer.go, pkg/ccm/vminfocache.go, pkg/vcdclient/client.go, pkg/vcdclient/vms.go
This PR makes changes to exchange the refresh token provided at the initialization of CPI to get access token at all top level functions called by kubernetes
Testing done:
* checked if refresh token is being exchanged with access token at the top level function - InstanceExistsByProviderID
@arunmk @ltimothy7
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/16)
=> [VCDA-2577] Changes to use access token at all top level functions

pkg/vcdclient/auth.go, pkg/vcdclient/client.go
When refreshing client using refresh token, isSysadmin boolean for the client should be manually set to true to overwrite the changes made by goVcd during SetToken()
@arunmk @ltimothy7
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/18)
=> manually set IsSysAdmin boolean while refreshing vcd client

pkg/ccm/loadbalancer.go, pkg/vcdclient/gateway.go
Get only prefix and loop through services to check if anything needs to be added. Hence even if http is the only service created, we'll mark the loadbalancer as incomplete and try to create the https service as well.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/20)
=> VCDA-2949: Ensure that loadbalancer creation retry will succeed

manifests/cloud-director-ccm.yaml, pkg/ccm/cloud.go, pkg/config/cloudconfig.go, pkg/vcdclient/auth.go, release/version
They were being passed as secrets and also as VCD config. This
change removes passing as configmap and uses only secrets with
retries.
This change also changes version of main branch to main-branch
so that people can point to the latest unreleased tip.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/32)
=> VCDA-3113: Passing user/secret as part of secrets was broken.

pkg/config/cloudconfig.go, pkg/vcdclient/auth.go
This was a fix locally on my machine.
Basically we read all parameters and try to find the UserOrg in case it is not specified.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/34)
=> VCDA-3151: fix regression with username/password and refreshToken

pkg/ccm/loadbalancer.go, pkg/vcdclient/gateway.go
Some small regressions: support native clusters and use L4 for TCP
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/42)
=> VCDA-3240: also handle nativeCluster

pkg/ccm/loadbalancer.go, pkg/vcdclient/auth_system_test.go, pkg/vcdclient/errors.go, pkg/vcdclient/gateway.go, pkg/vcdclient/gateway_system_test.go
This PR addresses the issue https://github.com/vmware/cloud-provider-for-cloud-director/issues/49 by updating some load balancer components like Virtual Service and Application Port Profile on update to `port` in LoadBalancer in Kubernetes
* Virtual Service Port should be updated whenever LoadBalancer's Port is changed
* Updating the LoadBalancer Port value triggers an EnsureLoadBalancer event
* EnsureLoadBalancer should in turn call Update loadbalancer
* Make sure that repeated updates with the same value doesn't make API calls as repeated PUT with the same values will fail
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …
=> Update Virtual Service, DNAT rule and App port profile on LB update

go.mod, pkg/vcdclient/auth.go, pkg/vcdclient/client.go, pkg/vcdclient/errors.go, pkg/vcdclient/gateway.go, pkg/vcdclient/rde.go, pkg/vcdclient/vms.go, pkg/vcdswaggerclient/api_defined_entity.go
VCDA-3389: This is to help reuse of code from CPI, CSI etc. The core differences are about making struct variable names public so that CSI can reuse them. The CSI usage will be added later.
There is a reference to `arunmk` but that will be removed as an additional commit.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/53)
=> Make CCM as the common base package to hold VCD details

pkg/vcdclient/auth.go, pkg/vcdclient/client.go
* Address issue with system administrator login using refresh token
* Try authenticating to system org and fall back to user org if it fails
Testing done:
* ran system tests
* Executed CPI as system admin and org admin
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/57)
=> [VCDA-3443] Set authentication as system org user before falling back to userorg

pkg/vcdclient/auth.go, pkg/vcdclient/auth_system_test.go, pkg/vcdclient/client.go
* Address issue with system administrator login using refresh token
* Try authenticating to system org and fall back to user org if it fails
Testing done:
* ran system tests
* Executed CPI as system admin and org admin
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/58)
=> [VCDA-3443] Set authentication as system org before falling back to userOrg

pkg/ccm/loadbalancer.go, pkg/vcdclient/gateway.go, pkg/vcdclient/gateway_system_test.go
* Updates to DNAT rule may put the gateway in a busy state
* This may cause successive updates to fail
* Fix the above issue by not making an update call if the DNAT rule has not been changed
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/56)
=> [VCDA-3448] Avoid updates to the DNAT rule if no chnage

pkg/config/cloudconfig.go
Ticket: VCDA-3513
- Updated cloudConfig to trim trailing slashes from host after parsing the config
- Testing Done:
- Created a cluster with host and trailing slash, resulting in coredns and csi pods to be stuck at pending state due
- Locally built CSI/CPI images with removed slashes and updated the pods and deployment and brought them back up to a running state
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/63)
=> [VCDA-3513] Handle trailing slashes to avoid broken API paths

pkg/vcdsdk/client.go, pkg/vcdsdk/common_system_test.go
* NewVCDClientFromSecrets() used to return a singleton client on every call.
* Singleton client will cause issues in CAPVCD and it is not really used in the code.
* This PR removes the singleton client
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/71)
=> Remove code that makes NewClientFromSecrets() return a singleton

pkg/ccm/instances.go, pkg/ccm/vminfocache.go, pkg/vcdsdk/org_test.go, pkg/vcdsdk/vapp.go, pkg/vcdsdk/vapp_test.go
* VApp name should be a parameter for all VApp based operations in vdcmanager
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/74)
=> Add back VApp name as function param in VDCManager

pkg/cpisdk/cpi_gateway_manager.go, pkg/vcdsdk/gateway.go
* Create virtual service should return the virtual service summary if the virtual service is still pending. This will ensure we can still use the returned virtual service if we want to.
* Add virtual service to VCDResourceSet just after Virtual service creation  even if Virtual service goes to pending state
* Necessary to update Virtual service in the vcdResourceSet during CAPVCD reconciliation.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/81)
=> Return virtual service summary if virtual service is pending

pkg/cpisdk/cpi_gateway_manager.go, pkg/vcdsdk/gateway.go, pkg/vcdsdk/ipam.go
This is to help with CAPVCD use case where a user may want to use internal IPs for control plane nodes. The use-case for ingress is not yet well defined and hence CPI does not have the changes yet.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/93)
=> VCDA-3813: Allow no tier0 in common core

pkg/cpisdk/cpi_gateway_manager.go, pkg/vcdsdk/gateway.go
This is to help CAPVCD use customer-specified IP for control-plane.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/94)
=> VCDA-3722: [common-core] allow passing in an IP to CreateLoadBalancer

pkg/vcdsdk/defined_entity.go
per klog documentation
```
// V reports whether verbosity at the call site is at least the requested level.
// The returned value is a boolean of type Verbose, which implements Info, Infoln
// and Infof
```
therefore, we cannot increase verbosity level of `Error` logs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/105)
=> VCDA-3875 increase verbosity of info logs

pkg/ccm/loadbalancer.go, pkg/vcdsdk/gateway.go
Return The allocated resources map when querying for load balancer.
This change helps CAPVCD add the LoadBalancer VCD resources after CAPVCD upgrade.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/106)
=> GetLoadBalancer() to return allocated resources map

pkg/ccm/loadbalancer.go, pkg/vcdsdk/gateway.go
Added nil checks for vsSummary as it could be nil even if error returned is nil.
Included fixes for VCDA-4025, VCDA-4026
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/110)
=> [VCDA-4015] Fix nil pointer exception during startup

pkg/vcdsdk/auth.go
* Change userorg in vcdAuthConfig to reflect the correct value
* If the attempt to authenticate with system org succeeds, set userorg as system
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/116)
=> [VCDA-3994] Fix incorrectly persisted userorg when system admin refresh tokens are used

manifests/cloud-director-ccm-crs.yaml, manifests/vcloud-configmap.yaml, pkg/config/cloudconfig.go
A new manifest file named `cloud-director-ccm-crs.yaml` has been created. This will be used by those installations that use CRS. This needs to be converted into a secret and used. (The documentation will later be added in CAPVCD repo).
There is a reference in this file to ClusterID coming in as a secret. (Env in line 165). So until that env is set, the CPI pod will be in a ConfigError loop. Once the secret is set, the pod will start up.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/119)
=> VCDA-4186: Add secret-based way to get the Cluster-id so that CRS can use it.

Dockerfile, manifests/cloud-director-ccm-crs.yaml, manifests/cloud-director-ccm.yaml
- Docker container should with USER nobody
- Add securityContext to deployment spec
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/121)
=> [VCDA-4204]Add security context to deployment manifest

Makefile, manifests/cloud-director-ccm-crs.yaml.template, manifests/cloud-director-ccm.yaml, manifests/cloud-director-ccm.yaml.template
This will embed the git sha in the tag of the image. To use the image of a particular git sha, use the git sha that references the image.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/125)
=> VCDA-4331: append git sha to dev builds

pkg/cpisdk/rde.go, pkg/vcdsdk/defined_entity.go, pkg/vcdsdk/defined_entity_test.go
* Avoid RDE updates when vcd resource is already present in the vcd resource set and there is no change in the vcd resource being added
* Tested by executing the tests
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/133)
=> [VCDA-4563] Reduce updates to RDE by only updating the VCD Resource set when there is a change

pkg/vcdsdk/common_system_test.go, pkg/vcdsdk/vapp.go, pkg/vcdsdk/vapp_test.go
Here we enable the autogenerate password so that templates which don't have this parameter set will still be able to get a password for remote console.
This is a common core change to be used in CAPVCD.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/132)
=> VCDA-4532: AutoGenerate Password for VMs

pkg/vcdsdk/gateway.go, pkg/vcdswaggerclient/api_org_vdc_networks.go
* Prevents system org user from caching an incorrect gateway in a scenario where there are more than one network with the same name, belonging to different org and connected to different tenant edge gateways
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/135)
=> [VCDA-4586] Add tenant context header to the get ovdc networks function

pkg/vcdsdk/defined_entity.go
* Clean up spammed etag logging statements in CAPVCD
* Increase the verbosity of logging level
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/134)
=> [VCDA-44481] Clean up logs spammed with “wrong etag” statements in CPI common code

pkg/vcdsdk/gateway.go, pkg/vcdswaggerclient/api_certificate_library_modified.go, pkg/vcdswaggerclient/vcdconstants.go
* Error should only be thrown when there are networks with duplicate names within an org
* Create a separate go file to store Tenant context constant
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/140)
=> [VCDA-4632] Fix detection of duplicates logic in getOvdcNetwork by name

pkg/vcdsdk/gateway.go, pkg/vcdswaggerclient/api_certificate_library_modified.go, pkg/vcdswaggerclient/vcdconstants.go
* Cherry pick fix for the duplicate detection logic in getOvdcNetwork() function
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/141)
=> Fix detection of duplicates logic in getOvdcNetwork by name (#140)

pkg/vcdclient/gateway.go, pkg/vcdclient/rde.go, pkg/vcdswaggerclient/api_certificate_library_modified.go, pkg/vcdswaggerclient/api_defined_entity.go, pkg/vcdswaggerclient/api_edge_gateway.go, pkg/vcdswaggerclient/api_edge_gateway_load_balancer_pool.go, pkg/vcdswaggerclient/api_edge_gateway_load_balancer_pools.go, pkg/vcdswaggerclient/api_edge_gateway_load_balancer_virtual_service.go, pkg/vcdswaggerclient/api_edge_gateway_load_balancer_virtual_services_modified.go, pkg/vcdswaggerclient/api_edge_gateway_nat_rule.go, pkg/vcdswaggerclient/api_edge_gateway_nat_rules.go, pkg/vcdswaggerclient/api_load_balancer_service_engine_group_assignments.go, pkg/vcdswaggerclient/api_org_vdc_network.go, pkg/vcdswaggerclient/api_org_vdc_networks.go, pkg/vcdswaggerclient/vcdconstants.go
* Cloud api requests should be scoped to the cluster's organization.
* fixes bugs where a system administrator user sees inconsistent behavior where VCD resources outside the cluster organization is being accessed.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/139)
=> [VCDA-4627] Cloud api calls should send in a tenant context header to scope requests to the cluster's organization

pkg/vcdsdk/gateway.go
- ignore errors if app port profile is not found during lb update
- add comments mentioning why the change is needed
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/157)
=> [VCDA-4740] ignore errors when app port profile is not found during lb update

pkg/ccm/loadbalancer.go
Use appProtocol only in case of HTTP/HTTPS/TCP so that:
1. services such as nginx that use the appProtocol can work well.
2. other services with unexpected appProtocol are allowed to pass through.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/162)
=> VCDA-4775: Ignore specified appProtocol

pkg/ccm/loadbalancer.go, pkg/vcdclient/gateway.go
* Ensure clean up of VCD resources even if loadbalancer fails to come up completely
* Tested with:
* CSE 3.1.3 cluster - Install Ingress using helm without specifying any cert annotations and then deleting the service with helm uninstall
* CSE 3.1.3 cluster - Install Ingress using helm and specifying invalid certificate and then deleting the service with helm uninstall
* CSE 3.1.3 cluster - Install Ingress using helm and loadbalancer came up successfully, performed helm uninstall and cleanly deleted everything
* CSE 3.1.3 cluster - Install ingress using helm and loadbalancer came up successfully, performed helm uninstall and forced it to fail by updating LB components at the same time to force busy error, saw it reconcile and delete remainder resources.
Signed-off-by: lzichong …
=> [VCDA-4776] Fix to ensure EnsureLoadBalancerDeleted is called for failed loadbalancer creations

schema/schema_1_1_0.json
* Created schema_1_1_0.json definition for CPI status section in CAPVCD cluster RDE
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/174)
=> [VCDA-4885] Create schema definition for CPI status section in capvcdCluter RDE

pkg/vcdsdk/vapp.go
Tested via automation testing by deleting a VM in VCD and observed that the Node in Kubernetes cluster was deleted.
CAPVCD, Projector, VCDKE repo doesn't seem to be using this method so other projects shouldn't need changes once common core updates
Error reference: https://github.com/vmware/cloud-provider-for-cloud-director/blob/main/pkg/ccm/instances.go#L171
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/186)
=> [VKCI-98] Fix for nodes not being deleted due to VM not found after deleted in VCD

pkg/ccm/loadbalancer.go
* Testings done:
Attempt LB deployment with invalid configurations which causes the load balancer to never come up, and then performing a delete and saw the VCD resources get cleaned up.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/179)
=> [VKCI-70] Fix to ensure VCD resources are cleaned up after deleting LB service even if LB failed during deployment

pkg/vcdsdk/ipam.go
Tested against VCD 10.4.1 GA using IP Spaces. Verified that CCM pod is no longer crashing when IP's can't be fetched:
E1222 01:39:59.854969       1 controller.go:307] error processing service default/ingress-nginx-controller (will retry): failed to ensure load balancer: unable to create loadbalancer for ports [[]vcdsdk.PortDetails{vcdsdk.PortDetails{Protocol:"HTTP", PortSuffix:"http", ExternalPort:80, InternalPort:30096, UseSSL:false, CertAlias:""}, vcdsdk.PortDetails{Protocol:"HTTPS", PortSuffix:"https", ExternalPort:443, InternalPort:32018, UseSSL:false, CertAlias:""}}]: [unable to get unused IP address from subnet []: [unable to get any ipRanges in gateway]]
Previously, the CCM pod would crash due to using Subnet.Values when it is null.
- - …
=> [VKCI-104] Fix for nil pointer exception when subnet is null from usage of IP Spaces

pkg/ccm/loadbalancer.go
CPI uses the appProtocol feature and tries to do some intelligent things such as set up Avi with HTTPS and a Cert in case the appProtocol is `https`.
Nginx has an `appProtocol: false` option by means of which one can control the `appProtocol`.
However this option is not yet available in ingresses such as Contour.
So we introduce a new annotation (`service.beta.kubernetes.io/vcloud-avi-ssl-no-termination`) to let CPI provide the same effect as disabling `appProtocol`. When this annotation is set to `"true"`, CPI will create a TCP LoadBalancer in Avi with the port. The expectation is that SSL termination will be provided by the ingress such as Contour / Nginx
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …
=> VKCI-97: Add annotation to skip Avi SSL termination for all protocols

pkg/vcdsdk/ipam.go
…ge of IP Spaces (#198)
* Fix for nil pointer exception when IP Spaces is being used resulting in null subnet
* CR of Aniruddh: correction for nil check
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/199)
=> [VKCI-104] Cherrypick - Fix for nil pointer exception when subnet is null from IP Spaces Usage

pkg/testingsdk/client.go, pkg/testingsdk/k8sclient.go, tests/e2e/loadbalancer_test.go
- add e2e tests for user specified load balancer IP feature.
- updated utils to create a load balancer type service by specifying a `loadBalancerIP`
Testing done:
- execute the e2e test.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/216)
=> [VKCI-69] Add tests for user specified load balancer IP address

pkg/vcdsdk/vapp.go
Testing: TKG 1.6.1 and 1.5 vm  correctly have guest script, and 98-* datasource file is created
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/220)
=> [VKCI-132] TKG VM creation for TKG 1.6.1 support

pkg/vcdsdk/vapp.go
Some users' naming policies enforce that the computer name matches the VM name.
This is also the default behavior in the VCD UI when provisioning a VM.
This PR replicates the default policy and sets the VM computerName field to the same values as the VM name.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/219)
=> Set ComputerName as vmName

pkg/testingsdk/client.go, pkg/testingsdk/k8sclient.go, pkg/testingsdk/vcd_utils.go
- query vApp templates from all catalogs
- get all nodes (including control plane)
- get current cluster's k8s version
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/243)
=> [VKCI-159][VKCI-161] add common functions to common testing core

manifests/cloud-director-ccm-crs.yaml, manifests/cloud-director-ccm-crs.yaml.template, manifests/cloud-director-ccm.yaml, manifests/cloud-director-ccm.yaml.template
- Update tolerations and node affinity selector key as `node-role.kubernetes.io/master` has been deprecated.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/240)
=> fix: update tolerations

pkg/testingsdk/k8sclient.go
error messages changed from `fmt.Errorf("error occurred while getting nodes")` to `fmt.Errorf("error occurred while getting nodes: [%v]", err)`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/246)
=> [VKCI-162] common testing core - updated getNodes() and getWorkerNodes() error messages

tests/e2e/loadbalancer_test.go
* Move namespace/deployment creation inside the test spec to prevent duplicate namespace creation during tests
* Ensured tests are able to run without any issues/modifications
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/253)
=> [VKCI-181] Move namespace/deployment creation inside the test spec to prevent duplicate namespace creation during tests

Dockerfile, Makefile
- Move to a static binary and remove symbols
```bash
67 MB  COPY /build/vcloud/cloud-provider-for-cloud-director . # buildkit
```
```bash
47 MB  COPY /build/vcloud/cloud-provider-for-cloud-director . # buildkit
```
- Move from Photon 4 base to scratch image
```bash
after                    latest            98c2e649c766   5 minutes ago       47.4MB
before                   latest            f499247c66d9   8 minutes ago       170MB
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/255)
=> fix: move to scratch image and static binary

Makefile, artifacts/bom.json.template, artifacts/default-cloud-director-ccm-crs-airgap.yaml.template, artifacts/dependencies.txt.template, manifests/cloud-director-ccm-crs.yaml.template, manifests/cloud-director-ccm.yaml.template
* Pushes airgapped artifacts with `$version.$gitSha`, so that it matches the dev image tags in the manifests
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/259)
=> [VCDA-5806] Ensure airgapped containers and binary images have same tag

pkg/testingsdk/entities.go, pkg/testingsdk/rde_utils.go, tests/e2e/node_test.go
* Update kubeconfig retrieval such that it can support both RDE entity type 1.1.0, and 1.2.0
* Improvements to Node LCM tests to skip rather than outright fail when cluster does not have 2 or more worker nodes
* Tested against 2 clusters:
* RDE 1.1.0 – 1x CP, 2x Worker -≥ LCM/LB tests passed
* RDE 1.2.0 – 1x CP, 1x Worker -> LCM tests skipped due to 1 worker, LB tests passed
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/262)
=> [VKCI-196] Update testing common core to add new way of retrieving kubeconfig + minor improvements to Node LCM tests

pkg/testingsdk/entities.go, pkg/testingsdk/rde_utils.go, tests/e2e/node_test.go
…beconfig + minor improvements to Node LCM tests (#262)
* Update kubeconfig retrieval so it supports both RDE 1.1.0, 1.2.0
* Update Node LCM tests so that it does not outright fail if cluster does not have 2+ worker nodes
* Add a nil check for capvcd status map in the event that it's missing from rde.capvcd.status
* Correct condition check + cluster id logging
* Address Yan CR: Add error check for semver versions, add comment for VCD versions
---------
(cherry picked from commit …
=> [VKCI-196] Cherrypick – Update testing common core to add new way of retrieving kubeconfig

tests/e2e/loadbalancer_test.go
* By waiting for the Deployment to come up, we will have ensured the server is up and running, and only then we should make the GET requests.
* Added `WaitForDeployment()` as part of the test.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/271)
=> [VKCI-203] Fix inconsistent 503 from GET reqs by waiting for Deployment to be ready

pkg/testingsdk/k8sclient.go
* Increase timeout durations for polling in testingsdk common core
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/277)
=> [VKCI-207] Increase timeouts for testingsdk

pkg/testingsdk/k8sclient.go
Add additional timeout for getNodes
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/278)
=> [VKCI-207] Add additional timeout for getNodes

manifests/cloud-director-ccm-crs.yaml, manifests/cloud-director-ccm-crs.yaml.template, manifests/cloud-director-ccm.yaml, manifests/cloud-director-ccm.yaml.template
- changes done as per https://kubernetes.io/docs/tasks/configure-pod-container/migrate-from-psp/#eliminate-non-standard-options
- remove the following fields from deployment spec
- runAsGroup
- fsGroup
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/280)
=> [VKCI-212] Remove fields from CPI deployment as a result of PodSecurityPolicy deprecation and removal from Kubernetes

pkg/testingsdk/k8sclient.go, tests/e2e/e2e_suite_test.go, tests/e2e/loadbalancer_test.go, tests/e2e/utils/utils.go
* Uses environment variables to indicate whether it's an airgap run or not, and use correct images for Deployment creation
* Add additional check for Container's status on top of PodRunning state before marking Deployment as ready
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/283)
=> [VKCI-214] Add support for airgap and staging images, add ContainerStatus check to DeploymentReady check

tests/kubeconfig_test/kubeconfig_retrieval_test.go, tests/kubeconfig_test/kubeconfig_suite_test.go, tests/kubeconfig_test/utils/utils.go
* Uses vcdClient to fetch kubeconfig from RDE
* Saves it to a directory for future use such as Jenkins agents
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/287)
=> [VKCI-221] Create test for fetching kubeconfig, and saving it to specified path

tests/e2e/e2e_suite_test.go
During merge of cse-2-24-next branch into main, the private registry info in e2e test was overwritten to an old private registry. This PR reverts the change related to private registry in e2e tests.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/310)
=> Fix CPI test for air-gapped env

pkg/vcdswaggerclient_36_0/model_edge_load_balancer_pool_modified.go, pkg/vcdswaggerclient_37_2/model_edge_load_balancer_pool_modified.go
The issue was that, for one particular case in LB pool creation, we would use 0 to indicate that the graceful disable timeout would be immediate. However 0 is a null value and the omitempty was dropping the field. Since the field was dropped, VCD API server was treating the value as not sent, and using the default value for this parameter which was 1. Hence the intended graceful disable timeout was never set up.
The change is to remove all omitempty values. The core advantage of omitempty is in messaging systems where message size is important. So reducing the unnecessary fields will help make messaging smaller. In the case of the VCD API, we don't need to have optimized messages. However accuracy is key. Thus, removing the omitempty globally will not cause much harm but will ensure that …
=> VKCI-244: remove all omitempty from swagger

tests/e2e/loadbalancer_test.go, tests/e2e/utils/cpi_rde_utils.go
* Poll for RDE updates instead of immediate failure
* Remove error return to let test assertion decide
---------
Cherrypick 85d974d from main
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/316)
=> [Cherrypick][VKCI-237][Testing] Poll for RDE updates instead of immediate failure (#314)

pkg/vcdsdk/vapp.go, pkg/vcdsdk/vapp_test.go, pkg/vcdsdk/vm_types.go
1. VM creation was nested and using redundant APIs to get the same information. 
2. VM creation had some complex logic around multi-VM creation and power-on. Those were added by me and the intern a long time ago, but they are not relevant now. They also hinder readability and ability to maintain and add new code.
3. ExtraConfig update updates one config at a time and each update is slow. They can be batched. (For a single-config update, one can use a single-element map).
4. There were some functions that were blocking with the task. Now these functions are essentially asynchronous with the task being returned to the caller. It is a simple pattern to block in the caller.
5. Some basic decomposition into functions to help readability.
All of the changes are in the common core. They affect …
=> VKCI-281,282: Simplify VM creation and ExtraConfig updates

artifacts/bom.json.template, artifacts/dependencies.txt.template
Updates dependencies.txt.template to use 'vmware-cloud-director/cluster-api-provider-cloud-director' as part of image path for consistency
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/332)
=> [VCDA-6990] Update dependencies.txt.template to use vmware-cloud-director for image path

Makefile, manifests/vcloud-configmap.yaml, pkg/ccm/cloud.go, pkg/ccm/common.go, pkg/ccm/instances.go, pkg/ccm/instancesv2.go, pkg/ccm/k8shelper.go, pkg/ccm/vminfocache.go, pkg/config/cloudconfig.go, pkg/config/zonemap.go, pkg/vcdsdk/vapp.go
This change brings in a the multiAZ aspect to the CPI. The CPI registers nodes, and the nodes are in multiple vApps. So the vApps need to be discovered in multiple OVDCs. The representation of OVDCs is in a configmap which has the following example format
```
---
apiVersion: v1
kind: ConfigMap
metadata:
name: vcloud-capvcd-zones
namespace: kube-system
data:
vcloud-cse-zones.yaml: |+
zoneType: dcgroup
zones:
- name: zone1
ovdcName: <ovdc of zone1>
- name: zone2
ovdcName: <ovdc of zone2>
- name: zone3
ovdcName: <ovdc of zone3>
---
```
To trigger usage of this zoneMap, and also to ensure backward compatibility, this feature is triggered by a flag in the CPI configmap variable `isZoneEnabledCluster`:
```
apiVersion: v1
kind: ConfigMap
metadata:
name: vcloud-ccm-configmap
namespace: …
```
=> VKCI-254,255,257: look at multiple OVDCs in order to register the VM

pkg/vcdsdk/vapp.go, pkg/vcdsdk/vapp_test.go
DeleteVM() function currently waits on the delete VM task to complete before it returns.
This change will make DeleteVM() asynchronous and also returns the task object for the caller to help poll the delete VM task status
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/338)
=> [VKCI-285] update DeleteVM() function to make it asynchronous

pkg/util/util.go, pkg/util/util_test.go, pkg/vcdsdk/vapp.go
Tested using a unit test. This follows VMware Cloud Director specifications.
(Sample password is `%#w9Q83uP!kq7R6`)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/339)
=> VKCI-284: Use the same character-set as VCD for passwords

Makefile
* Updates the Makefile with all the necessary targets that will only be used for gobuild
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/337)
=> [VCDA-6932] Consolidate makefile with all the necessary targets

pkg/vcdsdk/common_system_test.go, pkg/vcdsdk/gateway.go, pkg/vcdsdk/ip_spaces_test.go
Added method FetchIpSpacesBackingGateway to gateway.go
Testing done:
Added test TestFetchIpSpacesBackingGateway to ip_spaces_test.go
---------
Signed-off-by: Aritra Sen <sena@sena0MD6R.vmware.com>
Co-authored-by: Aritra Sen <sena@sena0MD6R.vmware.com>
(cherry picked from commit a38d62ea9ece0958f8931c63ab19481957dc1df3)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/344)
=> [x-port][VKCI-292] Implement method to fetch Ip Spaces associated with a gateway (#343)

pkg/vcdsdk/gateway.go, pkg/vcdsdk/ip_spaces_test.go
Added methods :
FilterIpSpacesByType
AllocateIpFromIpSpace
FindIpAllocationByIp
FindIpAllocationByMarker
MarkIpAsUsed
MarkIpAsUnused
ReleaseIp
Testing Done:
Added the following test in ip_spaces_test.go to test all the above mentioned methods TestIpSpaceOperations
---------
Signed-off-by: Aritra Sen <sena@sena0MD6R.vmware.com>
Co-authored-by: Aritra Sen <sena@sena0MD6R.vmware.com>
(cherry picked from commit 74fa1096927c1e708efd2b4560debd49802aaa57)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/346)
=> [x-port][VKCI-293] Add methods to allocate, release, update Ip Space Allocations (#345)

pkg/ccm/loadbalancer.go, pkg/vcdsdk/gateway.go
Added methods:
reserveIpForLoadBalancer in gateway.go
getLoadBalancerIpClaimMarker in loadbalancer.go
Updated methods:
createLoadBalancer in loadbalancer.go
CreateLoadBalancer in gateway.go
to enable reserving Ip for load balancers from Ip Spaces if the gateway supports it.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/347)
=> [VKCI-294] Reserve Ip from Ip Space during Load Balancer creation

pkg/ccm/loadbalancer.go, pkg/vcdsdk/gateway.go, pkg/vcdsdk/gateway_system_test.go, pkg/vcdsdk/ip_spaces_test.go
Added method:
ReleaseIpFromLoadBalancer in gateway.go
Updated method:
DeleteLoadBalancer in gateway.go
Testing Done:
Add testcase TestIpAllocationAndReleaseToLoadBalancer to ip_spaces_test.go
Fixed broken tests in gateway_system_test.go
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/349)
=> [VKCI-295] Release IP on load balancer Deletion

pkg/ccm/loadbalancer.go, pkg/vcdsdk/gateway.go, pkg/vcdsdk/gateway_system_test.go, pkg/vcdsdk/ip_spaces_test.go
Added method:
ReleaseIpFromLoadBalancer in gateway.go
Updated method:
DeleteLoadBalancer in gateway.go
Testing Done:
Add testcase TestIpAllocationAndReleaseToLoadBalancer to ip_spaces_test.go Fixed broken tests in gateway_system_test.go
---------
Signed-off-by: Aritra Sen <sena@sena0MD6R.vmware.com>
Co-authored-by: Aritra Sen <sena@sena0MD6R.vmware.com>
(cherry picked from commit af504c145ad5ff8485682b0fd67d12a126836606)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/350)
=> [x-port][VKCI-295] Release IP on load balancer Deletion (#349)

tests/e2e/e2e_suite_test.go, tests/e2e/loadbalancer_test.go
Current load balancer tests rely on IP block based network/gateway and will fail if ran against an IP Space based network/gateway.
Added early returns in these tests to make sure they run against only infra they were written for.
=> Update load balancer e2e test for ip space setups

pkg/vcdsdk/gateway.go
If the OVDC network is a DC group network, `vdc.GetNsxtEdgeGatewayByName(edgeGatewayName)` will return "EntityNotFound" error. This is because the govcd function will internally filter with `"ownerRef.id=="+vdc.Vdc.ID` and the `ownerRef.id` in case of  a DC group network is the ID of the DC group.
The solution used in this PR is to use the `org` GoVCD object to fetch the `edgeGateway` object.
Testing: Used this code in CAPVCD and saw that a right response is given for `IsUsingIPSpace()` function
=> [VKCI-306] get the gateway using the org object instead of the VDC

pkg/vcdsdk/gateway.go
error comparison in `IsUsingIPSpaces()` fix
=> [VKCI-306] fix error comparison

pkg/ccm/vminfocache.go, pkg/vcdsdk/org.go
use vapp name as the cluster name in a no-zone cluster.
=> [VKCi-310] fix logic for searching VMs for a no-zone cluster

artifacts/default-cloud-director-ccm-crs-airgap.yaml.template, manifests/cloud-director-ccm-crs.yaml, manifests/cloud-director-ccm-crs.yaml.template, manifests/cloud-director-ccm.yaml, manifests/cloud-director-ccm.yaml.template
When zone config map was added to the manifests, a mount path was missed to make it accessible by CPI code
=> [VKCI-313] error in the CPI manifests - missed mountPath in config

pkg/ccm/instances.go, pkg/ccm/instancesv2.go, pkg/ccm/vminfocache.go, pkg/vcdsdk/client.go, pkg/vcdsdk/org.go, pkg/vcdsdk/vapp.go, pkg/vcdsdk/vapp_test.go
This change brings in the option to either use an OVDC name or an OVDC ID for all operations.
This change does not support rename of OVDC names. If a user wants to rename in the future, they can use an ID rather than a name. So the onus is shifted to the client in deciding what to use to represent OVDCs.
In the case of CPI, the client is CSE and Kubernetes CLI.
=> VKCI-312: Allow OVDC name or ID to be passed as an input parameter

pkg/ccm/loadbalancer.go, pkg/ccm/vminfocache.go, pkg/testingsdk/client.go, pkg/testingsdk/vcd_utils.go, pkg/vcdsdk/gateway.go, tests/e2e/utils/cpi_vcd_utils.go
In some cases, the name was compared and used. This change fixes up those cases as well.
1. There was a comparison of the identifier with the vdc.Name. This was fixed.
2. There were numerous places where the ovdcName was used as a variable. This has also been fixed.
=> VKCI-314: fixup regressions in using OVDC ID

pkg/vcdsdk/gateway.go
DC Group networks return a nil OVDC
=> VKCI-317: Handle null OVDC in OVDCNetwork lookup

pkg/ccm/vminfocache.go, pkg/testingsdk/client.go, tests/e2e/e2e_suite_test.go, tests/e2e/node_test.go, tests/e2e/utils/cpi_vcd_utils.go, tests/e2e/utils/node_utils.go
Load Balancer CRUD tests do not change.
Node LCM tests need changes to search the node VM in a particular VDC.
This PR also contains a fix for one of the Node LCM tests where the node object is not deleted by CPI when the node VM is deleted in VCD
=> [VKCI-256, VKCI-320] Update ginkgo tests for multi az scenario

pkg/vcdsdk/auth.go, pkg/vcdsdk/gateway.go
CPI didn't support Datacenter Group networks because the method GetNsxtEdgeGatewayByName can't handle datacenter group networks. In this PR we have replaced the method with GetNsxtEdgeGatewayById to avoid the issue.
Additionally, added support for Proxy in SwaggerClient.
Testing done:
on a fresh VCD 10.5.1 setup
* Created an IP space
* Created IP space uplink in the PVDC
* Created two OrgVDC that are being powered by this PVDC
* Created a data center group from these two Org VDCs
* Created a stretched edge gateway and a data center org vdc network
* Ran the IP space test : TestGatewayUsingIpSpaces
```
=== RUN   TestGatewayUsingIpSpaces
I0724 14:39:24.036255   58260 auth.go:50] Using VCD OpenAPI version [37.2]
I0724 14:39:25.270434   58260 auth.go:74] Running module as sysadmin [false] …
```
=> Add support for Datacenter Group network in CPI
