vmware/cloud-provider-for-cloud-director

manifests/cloud-director-ccm.yaml

Signed-off-by: ltimothy <ltimothy@vmware.com>
Updating image url for cloud-director-ccm.yaml

updated image url

---

manifests/vcloud-basic-auth.yaml
manifests/vcloud-configmap.yaml

Signed-off-by: ltimothy <ltimothy@vmware.com>

using generic field values for configs

---

manifests/cloud-director-ccm.yaml
manifests/vcloud-configmap.yaml
pkg/ccm/cloud.go
pkg/config/cloudconfig.go

[VCDA-2680 and VCDA-2742] Waiting for basic auth credentials and generic config fields

---

pkg/vcdswaggerclient/api_defined_entity.go

Signed-off-by: ltimothy <ltimothy@vmware.com>
@arunmk

updating RDE with etag fix

---

pkg/vcdclient/gateway.go
pkg/vcdclient/gateway_system_test.go

Signed-off-by: ltimothy7 <66969084+ltimothy7@users.noreply.github.com>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/9)

[VCDA-2892] update RDE with external vip

---

README.md

Changed structure slightly, added right versions and a Beta plan-B section.

VCDA-2874: Changes needed for Beta

---

manifests/cloud-director-ccm.yaml
pkg/ccm/loadbalancer.go
pkg/vcdclient/gateway.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/11)

[VCDA-2888 & VCDA-2901] Vs name and dnat idempotent fix

---

cmd/ccm/main.go
manifests/cloud-director-ccm.yaml
manifests/vcloud-basic-auth.yaml
pkg/ccm/cloud.go
pkg/ccm/instances.go
pkg/ccm/k8shelper.go
pkg/ccm/loadbalancer.go
pkg/ccm/vminfocache.go
pkg/config/cloudconfig.go
pkg/config/cloudconfig_test.go
pkg/util/util.go
pkg/vcdclient/auth.go
pkg/vcdclient/auth_system_test.go
pkg/vcdclient/client.go
pkg/vcdclient/common_system_test.go
pkg/vcdclient/gateway.go
pkg/vcdclient/gateway_system_test.go
pkg/vcdclient/gateway_unit_test.go
pkg/vcdclient/vms.go
release/version
testdata/config_test.yaml
version/version.go

Create function to get access token from refresh token
Create function to check if the user is a system administrator
Use Access token to create vcd client
Testing done:
* Created a cluster with CPI running using the refresh token supplied from CSE
@arunmk @ltimothy7
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/12)

[VCDA-2577] Consume machine user token in CPI

---

Dockerfile

Tested to see that containers came up
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/14)

VCDA-2896: Use photon as base image

---

pkg/vcdclient/auth.go
pkg/vcdclient/client.go

Re-create swagger client with updated access token

[VCDA-2948] Fix swagger client not being refreshed

---

pkg/vcdclient/gateway.go

Ensure that we don't fail while we cache gateway details so that we can later decide if we need to support lb or not.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/21)

VCDA-2694: Allow NodeLCM to proceed for non-NSX-T networks

---

pkg/ccm/loadbalancer.go

CPI was returning an error in such cases.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/25)

VCDA-3095: Return LB if already created

---

pkg/ccm/loadbalancer.go
pkg/vcdclient/gateway.go
pkg/vcdclient/gateway_system_test.go
pkg/vcdswaggerclient/api_certificate_library_modified.go

Also allow arbitrary port numbers for CPI
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/26)

VCDA-3039, 3038: Use org name in cert query

---

scripts/generate-k8s-log-bundle.sh

Basic script to dump logs into a tarball
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/27)

VCDA-3006: Script to dump k8s logs

---

pkg/ccm/loadbalancer.go
pkg/vcdclient/gateway.go
pkg/vcdclient/gateway_system_test.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/28)

VCDA-3108: Allow multiple ports to be specified for http and https

---

README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/30)

VCDA-3109: Add details of patches to README

---

pkg/util/defined_entity_util.go
pkg/vcdclient/gateway.go

* Make sure that RDE updates doesn't cause hard failures in CPI
* Update CAPVCD RDE if the cluster RDE is of type CAPVCD cluster
Testing done:
* Installed ingress and checked if virtual IPs are getting updated in CAPVCD RDE.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/33)

[VCDA-3047]Update virtual ips for capvcd rde in CPI

---

pkg/ccm/loadbalancer.go
pkg/vcdclient/errors.go
pkg/vcdclient/gateway.go
pkg/vcdclient/gateway_system_test.go
pkg/vcdclient/rde.go
pkg/vcdswaggerclient/api_edge_gateway_load_balancer_virtual_services_modified.go

1. Fixup deletion of multiple ports. Also fixup update of LB.
2. Decide if SSL needed based on annotation
a. Also get cert based on annotation
3. Add L4 LB support
4. Support NO_RDE_ prefix
5. Add port to DNAT rule
6. Some small refactoring around RDE
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/36)

VCDA-3189: Multiple fixes to enable HTTPS cleanly

---

pkg/util/defined_entity_util.go

Change Nss from "capvcd" to "capvcdCluster"
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/38)

Change Nss to capvcdCluster

---

README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/46)

VCDA-3242: mention OrgAdmin user for cert; remove details of cert name

---

pkg/ccm/loadbalancer.go

* Changes to nodePort, port will trigger EnsureLoadBalancer Events
* To handle these changes, we should update load balancer in VCD
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/50)

Fix updates to nodePort and port properties in LB service

---

pkg/vcdclient/auth_system_test.go
pkg/vcdclient/client.go

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/55)

Fix vcd client to be compatible with CSI

---

pkg/util/defined_entity_util.go

* Version of the entity type should not be used for comparison
* Compare entity type nss and entity type vendor to determine if entity type is capvcdCluster or nativeCluster
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/54)

[VCDA-3421] Compare only vendor and nss to determine entity type

---

README.md

* Doc changes for 1.1.1 release
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/60)

Update README for 1.1.1 release

---

pkg/vcdsdk/vapp.go
pkg/vcdsdk/vapp_test.go

* This PR fixes some test functions which I missed committing to in my previous PR.
Testing done:
* make ccm
* run tests
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/67)

Test fixes which were missed in commit for CPI common library

---

pkg/vcdsdk/vapp.go
pkg/vcdsdk/vapp_test.go

* Vdc manager method to add metadata
* Vdc manger method to add vms to vapp with storage profile
Testing done:
* run system tests
* make ccm
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/70)

Add missing functions to common library

---

pkg/vcdsdk/client.go

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/73)

Use newUserOrg and newUsername to get the auth config (error from rebase)

---

pkg/ccm/instances.go
pkg/ccm/vminfocache.go
pkg/vcdsdk/org_test.go
pkg/vcdsdk/vapp.go
pkg/vcdsdk/vapp_test.go

* add back VApp name as function param in VDCManager
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/75)

[VCDA-3670] Add back VApp name as function param in VDCManager (#74)

---

pkg/config/cloudconfig.go
pkg/vcdsdk/auth_system_test.go
pkg/vcdsdk/client.go
pkg/vcdsdk/common_system_test.go
pkg/vcdsdk/gateway_system_test.go
pkg/vcdsdk/org_test.go
pkg/vcdsdk/vapp_test.go
testdata/vcd_info.yaml

* Remove references of `github.com/vmware/cloud-provider-for-cloud-director/pkg/config` from all files in `vcdsdk`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/77)

[VCDA-3669] Remove dependency on CPI's config in vcdsdk

---

pkg/vcdsdk/vapp.go

add `GetMetadataByKey` function in `vapp.go` in CPI code base for vkp branch
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/79)

[VCDA-3677] add GetMetadataByKey function in CPI vkp code base

---

pkg/vcdsdk/vapp.go

add `GetMetadataByKey` function in `vapp.go` in CPI code base
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/78)

[VCDA-3677] add GetMetadataByKey in CPI code base

---

pkg/cpisdk/cpi_gateway_manager.go
pkg/vcdsdk/gateway.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/86)

VCDA-3795: Refactor CPISDK to call LB creation from VCDSDK

---

manifests/cloud-director-ccm.yaml
release/version

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/90)

VCDA-3736: Point VKP branch to separate docker container

---

pkg/vcdsdk/defined_entity.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/92)

Included vcdResourceName also as part of Error and Event definitions.

---

manifests/vcloud-configmap.yaml
pkg/ccm/cloud.go
pkg/ccm/k8shelper.go
pkg/ccm/loadbalancer.go
pkg/config/cloudconfig.go
pkg/cpisdk/cpi_gateway_manager.go
pkg/util/set.go
pkg/util/set_test.go
pkg/vcdsdk/auth_system_test.go
pkg/vcdsdk/client.go
pkg/vcdsdk/gateway.go
pkg/vcdsdk/gateway_system_test.go
pkg/vcdsdk/ipam.go
pkg/vcdsdk/ipam_test.go
pkg/vcdsdk/org.go
pkg/vcdsdk/vapp_test.go
pkg/vcdsdk/vm_types.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/89)

[VCDA-3422] CPI support for multiple virtual services with the same ip and different ports

---

pkg/cpisdk/cpi_gateway_manager.go
pkg/vcdsdk/gateway.go
pkg/vcdsdk/ipam.go

This reverts commit 9a10c07a00c64865d3d52b30ef86730ceeceb70b.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/97)

Revert "VCDA-3813: Allow no tier0 in common core (#93)"

---

pkg/vcdsdk/client.go

Tested locally by replacing CPI dependency in CAPVCD go.mod with local changes
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/101)

VCDA-3741 Fix the log message whenever there is an authentication error

---

pkg/vcdsdk/client.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/103)

VCDA-3741 auth logging error vkp sync

---

pkg/ccm/loadbalancer.go
pkg/cpisdk/cpi_gateway_manager.go
pkg/vcdsdk/gateway.go
pkg/vcdsdk/ipam.go

This is somewhat also needed for VCDA-3880
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/102)

VCDA-3881: changes to make health monitor configurable

---

pkg/ccm/loadbalancer.go
pkg/vcdsdk/gateway.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/104)

main merge to vkp

---

pkg/vcdsdk/vapp.go

* Temp Method to solve [VCDA-4051](https://jira.eng.vmware.com/browse/VCDA-4051) network busy issue.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/112)

[VCDA-4051] [TestFest][Beta-blocker] Routed network is busy completing vApp creation

---

Makefile
manifests/cloud-director-ccm.yaml
release/version

Also drop the `latest` suffix
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/113)

VCDA-4013: vkp branch builds 1.2.0-beta now

---

manifests/cloud-director-ccm.yaml
release/version

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/115)

VCDA-4092: make main point to internal harbor again

---

pkg/vcdsdk/auth.go

- log error message when authentication with refresh token against system org fails
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/118)

[VCDA-4175]log error message if failed to authenticate with the system org

---

pkg/vcdsdk/vapp.go

* Remove sleep time in GetOrCreateVApp
* Update the image under main branch
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/120)

[GA-Fix] Remove sleep time in GetOrCreateVApp

---

README.md

Docs to enable and disable wire-logging
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/124)

Add docs for wire-logging

---

pkg/vcdsdk/vapp.go

title
Signed-off-by: rliang88 <rliang@vmware.com>
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/126)

[VCDA-4196] switched vmNamePrefix and VAppName parameters in AddNewVM()

---

manifests/cloud-director-ccm-crs.yaml
manifests/cloud-director-ccm.yaml

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/128)

Image tags refresh with latest code

---

manifests/cloud-director-ccm-crs.yaml
manifests/cloud-director-ccm.yaml
pkg/ccm/cloud.go
pkg/cpisdk/rde.go

Add retry logic to UpgradeCPISectionInStatus function and make a hard failure if the upgrade fail
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/127)

[VCDA-4387 ]Add retry logic to upgrade CPI section of existing RDE

---

manifests/cloud-director-ccm-crs.yaml
manifests/cloud-director-ccm.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/129)

VCDA-4464: FC build for CPI

---

manifests/cloud-director-ccm-crs.yaml
manifests/cloud-director-ccm.yaml

* Switching back to internal harbor with last code change commit
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/131)

[VCDA-4510] Update imagetag to commit 98f137e

---

pkg/cpisdk/rde.go
pkg/vcdsdk/defined_entity.go
pkg/vcdsdk/gateway.go
pkg/vcdsdk/ipam.go
pkg/vcdswaggerclient/api_certificate_library_modified.go
pkg/vcdswaggerclient/api_defined_entity.go
pkg/vcdswaggerclient/api_edge_gateway.go
pkg/vcdswaggerclient/api_edge_gateway_load_balancer_pool.go
pkg/vcdswaggerclient/api_edge_gateway_load_balancer_pools.go
pkg/vcdswaggerclient/api_edge_gateway_load_balancer_virtual_service.go
pkg/vcdswaggerclient/api_edge_gateway_load_balancer_virtual_services_modified.go
pkg/vcdswaggerclient/api_edge_gateway_nat_rule.go
pkg/vcdswaggerclient/api_edge_gateway_nat_rules.go
pkg/vcdswaggerclient/api_load_balancer_service_engine_group_assignments.go
pkg/vcdswaggerclient/api_org_vdc_network.go
pkg/vcdswaggerclient/api_org_vdc_networks.go

* Add tenant context to all the cloud api requests
* Prevent system admin users to look outside the scope of the org for any operation.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/136)

[VCDA-4587] Add tenant context header to all the cloud api request

---

manifests/cloud-director-ccm-crs.yaml
manifests/cloud-director-ccm.yaml

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/137)

[VCDA-4617] Update image tag to the latest main from 10/7

---

manifests/cloud-director-ccm-crs.yaml
manifests/cloud-director-ccm.yaml

The earlier checkin had an issue. So using the right ticket to fix it.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/138)

VCDA-4224: point to the right images

---

manifests/cloud-director-ccm-crs.yaml
manifests/cloud-director-ccm.yaml

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/143)

[VCDA-4638] - Refresh CPI 1.2.z from updated commoncore

---

README.md

Doc changes for 1.1.2
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/145)

Update docs with 1.1.2 info

---

manifests/cloud-director-ccm.yaml

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/147)

[VCDA-4647] Update manifests for CPI 1.1.2

---

manifests/cloud-director-ccm-crs.yaml
manifests/cloud-director-ccm.yaml

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/149)

[VCDA-4664] Refresh CPI image with latest commit from main - 709327d

---

pkg/ccm/loadbalancer.go

* Cherrypicked from VCDA-4630 main branch.
* Tested against Ingress service creation: observed only worker nodes were being added to loadbalancer pools
* Scaled up worker nodes: observed only new worker node got added into loadbalancer pool
* Scaled down worker node: observed only the scaled down worker node were removed from loadbalancer pool
* Scaled up and down control plane nodes: observed no impact in loadbalancer pool containing the worker nodes
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/151)

[VCDA-4630] Remove control plane from node pools altogether (#148) into 1.2.z

---

manifests/cloud-director-ccm-crs.yaml
manifests/cloud-director-ccm.yaml

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/152)

[VCDA-4730] 10/24 - Refresh CPI 1.2.z image to commit faa6bd5

---

manifests/cloud-director-ccm-crs.yaml
manifests/cloud-director-ccm.yaml

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/155)

[VCDA-4744] Refresh CPI 1.2.z image up to commit ee1c9e6

---

open_source_license.txt

* Update OSL for CPI 1.2.0 GA
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/156)

[VCDA-4229] Update OSL for CPI 1.2.0 GA

---

open_source_license.txt

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/158)

[VCDA-4229] Update osl for CPI 1.2.0 GA (#156)

---

pkg/vcdsdk/gateway.go

* ignore errors when app port profile is not found during lb update
* Address review comment - log the error
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/159)

[VCDA-4740] ignore errors when app port profile is not found during lb update (#157)

---

pkg/ccm/loadbalancer.go

(cherry picked from commit 36fde07f97275e5a90847adcec9b5d83228765cf)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/163)

VCDA-4775: Ignore specified appProtocol (#162)

---

README.md

Signed-off-by: ltimothy7
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/165)

[VCDA-4367] Document certificate rights for https ingress to cluster author

---

manifests/cloud-director-ccm-crs.yaml
manifests/cloud-director-ccm.yaml

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/167)

[VCDA-4806] Update CPI main image tag to commit 8946fef

---

README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/169)

Rollback 1.2.0 docs before GA

---

README.md

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/175)

[VCDA-4884] Provide documentation on how to upgrade CPI to 1.1.3 in CSE Config

---

manifests/cloud-director-ccm-crs.yaml
manifests/cloud-director-ccm-crs.yaml.template
manifests/cloud-director-ccm.yaml
manifests/cloud-director-ccm.yaml.template

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/177)

Changed the registry to public repo (CPI 1.2 GA)

---

README.md

Minor correction on where to upload the certificates for HTTPS
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/189)

[VKCI-84] Correction from Trusted Certificates to Certificates Library

---

README.md

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/190)

[VKCI-84] Update README docs correction for Certificates in 1.0.x

---

README.md

…y (#189)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/191)

[VKCI-84] Cherrypicked from main - Correction from Trusted Certificates to Certificates Library

---

README.md

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/193)

[VKCI-84] Update README docs correction for Certificates in 1.0.0

---

release/version

Signed-off-by: ltimothy7 <ltimothy@vmware.com>
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/196)

updated release/version to 1.3.0

---

pkg/ccm/loadbalancer.go

Rearrange code so that proper error message gets logged in CPI when update load balancer fails.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/200)

[VKCI-106] fix error message logged when update load balancer fails

---

pkg/ccm/loadbalancer.go

(cherry picked from commit a07a6a9fa6a948526855e4f612eb12771bbfe4ae)
Rearrange code so that proper error message gets logged in CPI when update load balancer fails.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/202)

[VKCI-106] fix error message logged when update load balancer fails (#200)

---

manifests/cloud-director-ccm-crs.yaml
manifests/cloud-director-ccm.yaml

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/203)

[VKCI-107] Update CPI 1.3.z image in manifests to latest commit 

---

manifests/cloud-director-ccm-crs.yaml
manifests/cloud-director-ccm.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/206)

Update manifests for CPI 1.3.0 release 

---

manifests/cloud-director-ccm-crs.yaml
manifests/cloud-director-ccm.yaml

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/207)

Revert back to internal harbor for CPI images

---

pkg/testingsdk/vcd_utils.go

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/209)

[VKCI-89-Bugfix] Testing common core - Fix for org nil check

---

pkg/testingsdk/k8sclient.go
pkg/testingsdk/rde_utils.go

* fix errors in createDeployment()
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/210)

[VKCI-112] BugFix for testing common code: fix errors in createDeployment()

---

pkg/testingsdk/rde_utils.go

* params order are swapped
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/211)

[VKCI-112][Bug-Fix] params order are swapped

---

pkg/testingsdk/capiyaml_utils.go

Signed-off-by: rliang88 <rliang@vmware.com>
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/214)

[VKCI-118] migrated generic functions from rde projector ginkgo tests to common testing core

---

pkg/testingsdk/client.go

* VCD K8s CPI Update testing common core (Add waitForPVCDelete and waitForPVDelete)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/215)

[VKCI-119] VCD K8s CPI Update testing common core (Add waitForPVCDelete and waitForPVDelete)

---

pkg/cpisdk/rde.go

* Auto converter method for RDE.status.CPI
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/222)

[VKCI 119] Auto converter method for RDE.status.CPI

---

pkg/ccm/cloud.go
pkg/ccm/loadbalancer.go
pkg/vcdsdk/gateway.go
pkg/vcdsdk/gateway_system_test.go
tests/e2e/loadbalancer_test.go

* Add Ovdc check when getting ovdc network
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/231)

[VKCI-141][common-core] Add Ovdc check when getting ovdc network 

---

.gitlab-ci.yml
Makefile

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/224)

[VCDA-4849] Add build file to push image to registry

---

pkg/vcdsdk/gateway.go

Resolves https://github.com/vmware/cloud-provider-for-cloud-director/issues/236
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/235)

Check OrgVdc.name in getOVDCNetwork only if OrgVdc is not nil

---

open_source_license.txt
release/version

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/241)

[VKC-155] Update CPI version to 1.4.0, [VKCI-158] Update CPI OSL

---

pkg/testingsdk/client.go
pkg/testingsdk/k8sclient.go

* Remove Kubernetes util functions those only used in CSI
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/249)

[VKCI-166] Remove Kubernetes util functions those only used in CSI

---

pkg/testingsdk/client.go
pkg/testingsdk/k8sclient.go

* Update testingSdk - remove storageClass functions && add config inside TestingClient
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/250)

[VKCI-166] Update testingSdk Fix - remove storageClass functions && add config inside TestingClient

---

Makefile
manifests/cloud-director-ccm-crs.yaml
manifests/cloud-director-ccm-crs.yaml.template
manifests/cloud-director-ccm.yaml
manifests/cloud-director-ccm.yaml.template

Built and verified that the push works
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/256)

VKCI-184: Move to projects-stg as default internal registry

---

open_source_license.txt

* Update CPI 1.4.0 GA OSL in release branch
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/266)

[VKCI-198] Update CPI 1.4.0 GA OSL in release branch

---

open_source_license.txt

* update OSL file
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/268)

[VKCI-198] update OSL file

---

README.md

* updated docs
Signed-off-by: ltimothy7 <ltimothy@vmware.com>
* upgrade edits
Signed-off-by: ltimothy7 <ltimothy@vmware.com>
---------
Signed-off-by: ltimothy7 <ltimothy@vmware.com>
(cherry picked from commit abd8bcec97ae7a55ee04ace23e31805376ef15ad)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/270)

[cherry-pick][VKCI-202] Updated 1.4.0 docs (#269)

---

tests/e2e/loadbalancer_test.go

Cherry-pick dd93fca: Fix inconsistent 503 from GET reqs by waiting for Deployment Pod to come up
(cherry picked from commit dd93fcaf7ed785fecdb23a98ad625c4a2f9dff19)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/272)

[VKCI-203] Cherrypick: Fix inconsistent 503 from GET reqs by waiting for Deployment to be ready

---

manifests/cloud-director-ccm-crs.yaml
manifests/cloud-director-ccm-crs.yaml.template
manifests/cloud-director-ccm.yaml
manifests/cloud-director-ccm.yaml.template

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/276)

[Cherry pick] [VKCI-205] Update image reference with correct reg and tag

---

go.mod
go.sum
pkg/vcdsdk/vapp.go
vendor/github.com/sethvargo/go-password/LICENSE
vendor/github.com/sethvargo/go-password/password/generate.go
vendor/github.com/sethvargo/go-password/password/mock.go
vendor/modules.txt

- Use a library to generate a password
- set the password during VM creation
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/282)

[VKCI-210] [common-core] Generate a 15 char password during VM creation

---

Makefile
go.mod

* upgrade golang version to 1.20
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/285)

[VKCI-216] upgrade golang version to 1.20

---

Makefile
pkg/ccm/cloud.go
pkg/ccm/loadbalancer.go
pkg/cpisdk/rde.go
pkg/cpisdk/rde_system_test.go
release/release.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/291)

[VKCI-229] make version consistent and correct build arg

---

Makefile
pkg/ccm/cloud.go
pkg/ccm/loadbalancer.go
pkg/cpisdk/rde.go
pkg/cpisdk/rde_system_test.go
release/release.go

(cherry picked from commit 718f8c1a7b61d371a64827ac30c78e11ef56878b)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/293)

[VKCI-229] cherry pick make 718f8c1

---

pkg/vcdsdk/client.go

Signed-off-by: Sakthi Sundaram <sakthisunda@yahoo.com>
(cherry picked from commit 3218a80bb3617acae90d51095d3f01effb13c5af)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/295)

[VKCI-230] cherry pick commit from main 3218a80

---

open_source_license.txt

Update OSL file for CPI 1.4.1 GA
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/298)

[VKCI-224] Update OSL for CPI 1.4.1 GA

---

tests/e2e/e2e_suite_test.go

* Update test automation private harbor image to new registry
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/300)

[VKCI-234][Tests] Update the testing image to new registry

---

tests/e2e/e2e_suite_test.go

Update the testing image to new registry
(cherry picked from commit 654fda76e3ee3dbb8da24b7a718c0c7e6c81494f)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/301)

[VKCI-234][Tests] Cherrypick: Update the testing image to new registry (#300)

---

manifests/cloud-director-ccm-crs.yaml
manifests/cloud-director-ccm.yaml

- Update manifests for CPI 1.4.1 release
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/304)

update the manifests for CPI 1.4.1 release

---

README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/306)

Added CPI 1.4.1 upgrade instructions

---

README.md

added 1.4.1 upgrade instructions
Signed-off-by: Timothy Le <ltimothy@vmware.com>
(cherry picked from commit 033081c9b4ffc8118abdfd7d3024c793a0944df8)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/307)

Added CPI 1.4.1 upgrade instructions (#306)

---

pkg/vcdsdk/gateway.go

Cherrypick from main: Update virtual service key reference for inserting to set for RDE updates
(cherry picked from commit 29ad035d8fea9dc829918446fb16c5d0900862ba)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/318)

[VKCI-265][Cherry-pick] Update virtual service key reference for adding virtual IP to RDE

---

manifests/cloud-director-ccm-crs.yaml
manifests/cloud-director-ccm.yaml

Update manifests for CPI
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/325)

Update manifests for CPI to point to 1.5.0

---

open_source_license.txt

- updated osl for CPI 1.5.0
Signed-off-by: Sakthi Sundaram <sakthisunda@yahoo.com>
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/328)

[VKCI-270] Update OSL

---

open_source_license.txt

- updated osl for CPI 1.5.0
Signed-off-by: Sakthi Sundaram <sakthisunda@yahoo.com>
(cherry picked from commit 10f3cbb906d41b0c76939565f8e022fc079704d2)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/329)

[VKCI-270] Update OSL (cherry pick #328)

---

manifests/cloud-director-ccm-crs.yaml
manifests/cloud-director-ccm.yaml

update manifests to point to 1.6.0 image
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/327)

[VKCI-274] update manifests in main branch

---

Makefile

* Removes registry references from Makefile
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/334)

[VCDA-6928] Remove registry references in Makefile

---

pkg/vcdsdk/common_system_test.go
pkg/vcdsdk/gateway.go
pkg/vcdsdk/ip_spaces_test.go
testdata/ip_space_test.yaml

Added method IsUsingIpSpaces in gateway.go
Testing Done:
Added test : TestGatewayUsingIpSpaces in ip_spaces_test.go
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/341)

[VKCI-280] Add functionality in gateway.go to report if it is using Ip Spaces or not

---

pkg/vcdsdk/common_system_test.go
pkg/vcdsdk/gateway.go
pkg/vcdsdk/ip_spaces_test.go
testdata/ip_space_test.yaml

Added method IsUsingIpSpaces in gateway.go
Testing Done:
Added test : TestGatewayUsingIpSpaces in ip_spaces_test.go
---------
Signed-off-by: Aritra Sen <sena@sena0MD6R.vmware.com>
Co-authored-by: Aritra Sen <sena@sena0MD6R.vmware.com>
(cherry picked from commit 375a8e09ca44063ef74e7b8061325e401b4e740e)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/342)

[x-port][VKCI-280] Add functionality in gateway.go to report if it is using Ip Spaces or not (#341)

---

pkg/vcdsdk/common_system_test.go
pkg/vcdsdk/gateway.go
pkg/vcdsdk/ip_spaces_test.go

Added method FetchIpSpacesBackingGateway to gateway.go
Testing done:
Added test TestFetchIpSpacesBackingGateway to ip_spaces_test.go
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/343)

[VKCI-292] Implement method to fetch Ip Spaces associated with a gateway

---

pkg/vcdsdk/gateway.go
pkg/vcdsdk/ip_spaces_test.go

Added methods :
FilterIpSpacesByType
AllocateIpFromIpSpace
FindIpAllocationByIp
FindIpAllocationByMarker
MarkIpAsUsed
MarkIpAsUnused
ReleaseIp
Testing Done:
Added the following test in ip_spaces_test.go to test all the above mentioned methods
TestIpSpaceOperations
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/cloud-provider-for-cloud-director/345)

[VKCI-293] Add methods to allocate, release, update Ip Space Allocations

---

manifests/vcloud-capvcd-empty-zones.yaml

add content for the empty zone cofigmap.
This was missed in the previous PR

[VKCI-305] add content for the empty zone cofigmap

---

Makefile
go.mod
go.sum

* upgrade go version to v1.21.7

[VKCI-301] upgrade go version to v1.21.7

---

pkg/ccm/cloud.go
pkg/ccm/instancesv2.go
pkg/ccm/vminfocache.go
pkg/vcdsdk/org.go
pkg/vcdsdk/vapp.go
pkg/vcdsdk/zonemap.go

Move ZoneMap and SearchVMAcrossOVDCs function so that it can be reused by other components.

VKCI-299: Refactors to allow CSI to use multiAZ implementation

---

go.mod
go.sum
vendor/github.com/golang/protobuf/jsonpb/decode.go
vendor/github.com/golang/protobuf/jsonpb/encode.go
vendor/github.com/golang/protobuf/protoc-gen-go/descriptor/descriptor.pb.go
vendor/github.com/golang/protobuf/ptypes/any.go
vendor/modules.txt

[VKCI-308] update protobuf to 1.5.4

---

pkg/testingsdk/capiyaml_utils.go

- Add function 'CreateNewMachineDeploymentWithFailureDomain'

[VKCI-319] Add function 'CreateNewMachineDeploymentWithFailureDomain'

---

pkg/vcdswaggerclient_37_2/model_access_control_grant_modified.go

*** Ported over from `main` ***
* Add `memberId` field into the struct
* Rename file to track that it has been modified

Fix missing field in ACL
